apiVersion: v1
kind: Secret
metadata:
  name: bpa-1-secret-key
  labels:
    app: {{ template "global.name" . }}
    chart: {{ template "global.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    seed: {{ index (lookup "v1" "Secret" .Release.Namespace "bpa-1-secret-key").data "seed" | b64dec }}

type: Opaque
data:
  {{ if (lookup "v1" "Secret" .Release.Namespace "bpa-1-secret-key") -}}
  seed: {{ index (lookup "v1" "Secret" .Release.Namespace "bpa-1-secret-key").data "seed" }}
  {{- else -}}
  seed: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end -}} 