- name: my-registration.bcgov-mines-permitting
  version: 1.0.0
  description: The my-registration credential issued by bcgov-mines-permitting
  attributes:
    corp_num:
      description_en: Registration/Incorporation Number or Identifying Number
      label_en: Registration ID
      data_type: helper_uuid
      required: true
    registration_date:
      description_en: Date of Registration, Incorporation, Continuation or Amalgamation
      label_en: Registration Date
      data_type: ui_date
      required: false
    entity_name:
      description_en: The legal name of entity
      label_en: Name
      data_type: ui_name
      required: true
    entity_name_effective:
      description_en: Date current name became effective
      label_en: Name Effective Date
      data_type: ui_date
      required: true
    addressee:
      description: addressee
      data_type: ui_text
      required: true
    address_line_1:
      description: address_line_1
      data_type: ui_text
      required: true
    city:
      description: city
      data_type: ui_text
      required: true
    province:
      description: province
      data_type: ui_text
      required: true
    postal_code:
      description: postal_code
      data_type: ui_text
      required: true
    country:
      description: country
      data_type: ui_text
      required: true
    entity_status:
      description_en: Status of the entity (active or historical)
      label_en: Registration Status
      data_type: ui_select
      required: true
    entity_status_effective:
      description_en: Date status became effective
      label_en: Status Effective Date
      data_type: ui_date
      required: true
    entity_type:
      description_en: Type of entity incorporated or registered
      label_en: Registration Type
      data_type: ui_text
      required: true
    registered_jurisdiction:
      description_en: The jurisdiction an entity was created in
      label_en: Registered Jurisdiction
      data_type: ui_text
      required: false
    effective_date:
      description_en: Date Credential is effective
      label_en: Credential Effective Date
      data_type: ui_date
      required: true
    expiry_date:
      description_en: Date Credential expired
      label_en: Credential Expiry Date
      data_type: ui_date
      required: false
- name: bcgov-mines-act-permit.bcgov-mines-permitting
  version: 0.1.0
  description: The bcgov-mines-act-permit credential issued by bcgov-mines-permitting
  attributes:
    corp_num:
      description_en: Registration/Incorporation Number or Identifying Number
      label_en: Registration ID
      data_type: ui_text
      required: true
    entity_name:
      description_en: The legal name of entity
      label_en: Name
      data_type: ui_name
      required: true
    permit_id:
      description_en: Permit Identifying Number
      label_en: Permit ID
      data_type: helper_uuid
      required: true
    permit_no:
      description_en: Permit Number
      label_en: Permit Number
      data_type: ui_text
      required: true
    mine_no:
      description_en: Mine Number
      label_en: Mine Number
      data_type: ui_text
      required: true
    mine_class:
      description_en: Mine Class, Regional or Major?
      label_en: Mine Class
      data_type: ui_select
      required: true
    latitude:
      description_en: Approx Latitude of permitted actions
      label_en: Latitude
      data_type: ui_text
      required: true
    longitude:
      description_en: Approx Longitude of permitted actions
      label_en: Longitude
      data_type: ui_text
      required: true
    authorization_end_date:
      description_en: the last day the permitted actions are authorized
      label_en: Authorization End Date
      data_type: ui_date
      required: true
    inspector_name:
      description_en: Name of EMLI permitting Inspector
      label_en: Inspector Name
      data_type: ui_text
      required: true
    issued_date:
      description_en: Date Permit is issued
      label_en: Permit Issued Date
      data_type: ui_date
      required: true
    effective_date:
      description_en: Date permit is effective
      label_en: Credential Effective Date
      data_type: ui_date
      required: true
