default:
  APPLICATION_URL_VONX: $APPLICATION_URL/bcgov-mines-permitting/bcgov-mines-act-permit
  TEMPLATE_PATH: ../templates

  TOB_API_URL: http://localhost:8081/api/v2
  TOB_APP_URL: http://localhost:8080

  WALLET_SEED_VONX: bcgov-mines-permitting_000000000000000000000000000

  INDY_GENESIS_URL: http://localhost:9000/genesis

  LEDGER_PROTOCOL_VERSION: "1.6"
  AUTO_REGISTER_DID: false
  ISSUER_SECRET_KEY: super_secret_key
### eof ###
