# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

issuers:
  ghg-emissions-reporting:
    name: Ministry of Environment and Climate Change Strategy
    abbreviation: ghg-emissions-reporting
    url: https://www.ghg-emissions-reporting.ca/ghg-emissions-report-info-page
    email: info@ghg-emissions-reporting.ca
    logo_path: ../assets/img/ghg-emissions-reporting-logo.jpg
    endpoint: $ENDPOINT_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    credential_types:
    - description: The ghg-emissions-report credential issued by ghg-emissions-reporting
      schema: ggirc-act.ghg-emissions-report
      issuer_url: $ENDPOINT_URL/ghg-emissions-reporting/ghg-emissions-report
      label_en: Annual GHG Emissions Report
      abbreviation_en: GHG Emissions Report
      depends_on:
      - greenlight_registration
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        label_en: Registration
        source_id:
          input: corp_num
          from: claim
        type:
          input: my-registration.ghg-emissions-report
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: facility_name
            from: value
          value:
            input: facility_name
            from: claim
      - model: attribute
        fields:
          type:
            input: facility_location
            from: value
          value:
            input: facility_location
            from: claim
      - model: attribute
        fields:
          type:
            input: primary_activity_code
            from: value
          value:
            input: primary_activity_code
            from: claim
      - model: attribute
        fields:
          type:
            input: primary_activity_description
            from: value
          value:
            input: primary_activity_description
            from: claim
      - model: attribute
        fields:
          type:
            input: co2_fossil_emissions
            from: value
          value:
            input: co2_fossil_emissions
            from: claim
      - model: attribute
        fields:
          type:
            input: co2_biomass_emissions
            from: value
          value:
            input: co2_biomass_emissions
            from: claim
      - model: attribute
        fields:
          type:
            input: ch4_emissions
            from: value
          value:
            input: ch4_emissions
            from: claim
      - model: attribute
        fields:
          type:
            input: n2o_emissions
            from: value
          value:
            input: n2o_emissions
            from: claim
      - model: attribute
        fields:
          type:
            input: hfcs_emissions
            from: value
          value:
            input: hfcs_emissions
            from: claim
      - model: attribute
        fields:
          type:
            input: pfcs_emissions
            from: value
          value:
            input: pfcs_emissions
            from: claim
      - model: attribute
        fields:
          type:
            input: sf6_emissions
            from: value
          value:
            input: sf6_emissions
            from: claim
      - model: attribute
        fields:
          type:
            input: verification_body
            from: value
          value:
            input: verification_body
            from: claim
      - model: attribute
        fields:
          type:
            input: verification_result
            from: value
          value:
            input: verification_result
            from: claim
      - model: attribute
        fields:
          type:
            input: reporting_year
            from: value
          value:
            input: reporting_year
            from: claim
      - model: attribute
        fields:
          type:
            input: issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: issued_date
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
    - description: The my-registration credential issued by ghg-emissions-reporting
      schema: my-registration.ghg-emissions-report
      issuer_url: $ENDPOINT_URL/ghg-emissions-reporting/ghg-emissions-report
      label_en: TEST Registration
      abbreviation_en: Registration
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: corp_num
          from: claim
        type:
          input: my-registration.ghg-emissions-report
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: registration_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: registration_date
            from: claim
      - model: name
        fields:
          text:
            input: entity_name
            from: claim
          type:
            input: entity_name
            from: value
      - model: attribute
        fields:
          type:
            input: entity_name_effective
            from: value
          format:
            input: datetime
            from: value
          value:
            input: entity_name_effective
            from: claim
      - model: address
        fields:
          addressee:
            input: addressee
            from: claim
          civic_address:
            input: address_line_1
            from: claim
          city:
            input: city
            from: claim
          province:
            input: province
            from: claim
          postal_code:
            input: postal_code
            from: claim
          country:
            input: country
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_status
            from: value
          value:
            input: entity_status
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_status_effective
            from: value
          format:
            input: datetime
            from: value
          value:
            input: entity_status_effective
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_type
            from: value
          value:
            input: entity_type
            from: claim
      - model: attribute
        fields:
          type:
            input: registered_jurisdiction
            from: value
          value:
            input: registered_jurisdiction
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim

verifiers:
  bctob:
    name: BC OrgBook
    alias: $TOB_CONNECTION_NAME
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      agent_admin_url: $TOB_AGENT_ADMIN_URL

proof_requests:
  greenlight_registration:
    version: '1.0.0'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: Registered Corporation
          version: '1.0.3'
        attributes:
          - corp_num
          - legal_name

### eof ###
