# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

issuers:
  mines-permitting:
    name: Ministry of Energy, Mines and Low-carbon Innovation
    abbreviation: bcgov-mines-permitting
    url: https://www.bcgov-mines-permitting.ca/bcgov-mines-permitting-info-page
    email: info@bcgov-mines-permitting.ca
    logo_path: ../assets/img/bcgov-mines-permitting-logo.jpg
    endpoint: $ENDPOINT_URL

    details: 
      label_en: BC Mines Permitting
      abbreviation_en: Mines Permitting
      endpoint: $ENDPOINT_URL 
      
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    credential_types:
    - description: The bcgov-mines-act-permit credential issued by bcgov-mines-permitting
      schema: bcgov-mines-act-permit.bcgov-mines-permitting
      issuer_url: $ENDPOINT_URL/bcgov-mines-permitting/bcgov-mines-act-permit
      depends_on:
      - greenlight_registration
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        label_en: Registration
        source_id:
          input: registration_id
          from: claim
        type:
          input: registration.registries.ca
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: permit_id
            from: value
          value:
            input: permit_id
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_no
            from: value
          value:
            input: permit_no
            from: claim
      - model: attribute
        fields:
          type:
            input: mine_no
            from: value
          value:
            input: mine_no
            from: claim
      - model: attribute
        fields:
          type:
            input: mine_class
            from: value
          value:
            input: mine_class
            from: claim
      - model: attribute
        fields:
          type:
            input: latitude
            from: value
          value:
            input: latitude
            from: claim
      - model: attribute
        fields:
          type:
            input: longitude
            from: value
          value:
            input: longitude
            from: claim
      - model: attribute
        fields:
          type:
            input: authorization_end_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: authorization_end_date
            from: claim
      - model: attribute
        fields:
          type:
            input: inspector_name
            from: value
          value:
            input: inspector_name
            from: claim
      - model: attribute
        fields:
          type:
            input: issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: issued_date
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim

verifiers:
  bctob:
    name: BC OrgBook
    alias: $TOB_CONNECTION_NAME
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      agent_admin_url: $TOB_AGENT_ADMIN_URL

proof_requests:
  greenlight_registration:
    version: '1.0.0'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: Registered Corporation
          version: '1.0.3'
        attributes:
          - corp_num
          - legal_name


### eof ###
