# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: my-registration.bcgov-mines-permitting
  version: '1.0.0'
  description: The my-registration credential issued by bcgov-mines-permitting
  endpoint: $ENDPOINT_URL
  path: /bcgov-mines-permitting/my-registration
  # identify the attribute which identify the owning organization
  topic: corp_num
  # optionally identify the credential attribute to map to the TOB credential effective date
  effective_date: effective_date
  # optionally identify the credential attribute to map to the TOB credential revoked date
  revoked_date: expiry_date
  # optionally identify a dependant proof request
  #proof_request: dflow_registration
  attributes:
    corp_num:
      label_en: Registration ID
      description_en: Registration/Incorporation Number or Identifying Number
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: helper_uuid
      required: true
    registration_date:
      label_en: Registration Date
      description_en: Date of Registration, Incorporation, Continuation or Amalgamation
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: false
    entity_name:
      label_en: Name
      description_en: The legal name of entity
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_name
      required: true
    entity_name_effective:
      label_en: Name Effective Date
      description_en: Date current name became effective
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    entity_address:
      label_en: Address
      description_en: The address of entity
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_address
      required: true
    entity_status:
      label_en: Registration Status
      description_en: Status of the entity (active or historical)
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_select
      required: true
    entity_status_effective:
      label_en: Status Effective Date
      description_en: Date status became effective
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    entity_type:
      label_en: Registration Type
      description_en: Type of entity incorporated or registered
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    registered_jurisdiction:
      label_en: Registered Jurisdiction
      description_en: The jurisdiction an entity was created in
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: false
    effective_date:
      label_en: Credential Effective Date
      description_en: Date Credential is effective
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    expiry_date:
      label_en: Credential Expiry Date
      description_en: Date Credential expired
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: false

- name: bcgov-mines-act-permit.bcgov-mines-permitting
  version: '1.1.0'
  description: The bcgov-mines-act-permit credential issued by bcgov-mines-permitting
  endpoint: $ENDPOINT_URL
  # identify the attribute which identify the owning organization
  topic: corp_num
  # optionally identify the credential attribute to map to the TOB credential effective date
  effective_date: effective_date
  # optionally identify the credential attribute to map to the TOB credential revoked date
  #revoked_date: expiry_date
  # optionally identify a dependant proof request
  proof_request: greenlight_registration
  path: /bcgov-mines-permitting/bcgov-mines-act-permit
  attributes:
    corp_num:
      label_en: Registration ID
      description_en: Registration/Incorporation Number or Identifying Number
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    entity_name:
      label_en: Name
      description_en: The legal name of entity
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_name
      required: true
    permit_id:
      label_en: Permit ID
      description_en: Permit Identifying Number
      data_type: helper_uuid
      required: true
    permit_no:
      label_en: Permit Number
      description_en: Permit Number
      data_type: ui_text
      required: true
    mine_no:
      label_en: Mine Number
      description_en: Mine Number
      data_type: ui_text
      required: true
    mine_class:
      label_en: Mine Class
      description_en: Mine Class, Regional or Major?
      data_type: ui_select
      required: true
    latitude:
      label_en: Latitude
      description_en: Approx Latitude of permitted actions 
      data_type: ui_text
      required: true    
    longitude:
      label_en: Longitude
      description_en: Approx Longitude of permitted actions 
      data_type: ui_text
      required: true       
    authorization_end_date:
      label_en: Authorization End Date
      description_en: the last day the permitted actions are authorized 
      data_type: ui_date
      required: true 
    inspector_name:
      label_en: Inspector Name
      description_en: Name of EMLI permitting Inspector 
      data_type: ui_text
      required: true   
    issued_date:
      label_en: Permit Issued Date
      description_en: Date Permit is issued
      data_type: ui_date
      required: true
    effective_date:
      label_en: Credential Effective Date
      description_en: Date permit is effective
      data_type: ui_date
      required: true

### eof ###

