name: Build GHG IC

on:
  push:
    paths:
      - ".github/workflows/ghg_ic_build.yaml"
      - "services/ghg-orgbook-issuer-controller/**"
      - "!**/README.md"
    branches:
      - develop

env:
  SERVICE_CONTEXT: services/ghg-orgbook-issuer-controller/
  IMAGE: ghg-emissions-issuer
  ENV_TAG: dev

jobs:
  ghg-ic-build:
    name: ghg-ic-build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: login to oc registry
        run: |
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }} ${{ secrets.REGISTRY_HOST }}

      - name: build and tag
        run: |
          cd ${{ env.SERVICE_CONTEXT }}
          docker build -t ${{ env.IMAGE }}:${{ env.ENV_TAG }} -t ${{ env.IMAGE }}:${{ github.sha }} .
          docker tag ${{ env.IMAGE }}:dev ${{ secrets.REGISTRY_HOST }}/${{ secrets.IS_NAMESPACE }}/${{ env.IMAGE }}:${{ github.sha }}
          docker tag ${{ env.IMAGE }}:dev ${{ secrets.REGISTRY_HOST }}/${{ secrets.IS_NAMESPACE }}/${{ env.IMAGE }}:dev

      - name: push
        run: |
          docker push --all-tags ${{ secrets.REGISTRY_HOST }}/${{ secrets.IS_NAMESPACE }}/${{ env.IMAGE }}
