---
kind: Template
apiVersion: v1
metadata:
    name: ${NAME}-build-template
objects:
    - kind: ImageStream
      apiVersion: v1
      metadata:
          name: ${NAME}
          labels:
              name: ${NAME}
              app: ${APP_NAME}${SUFFIX}
              app-group: ${APP_GROUP}

    - kind: BuildConfig
      apiVersion: v1
      metadata:
          name: ${NAME}
          labels:
              name: ${NAME}
              app: ${APP_NAME}${SUFFIX}
              app-group: ${APP_GROUP}
      spec:
          triggers:
              - type: ConfigChange
              - type: ImageChange
                imageChange: {}
          runPolicy: Serial
          source:
              type: Git
              git:
                  uri: ${GIT_REPO_URL}
                  ref: ${GIT_REF}
              contextDir: ${SOURCE_CONTEXT_DIR}
          strategy:
              type: Source
              sourceStrategy:
                  from:
                      kind: ${SOURCE_IMAGE_KIND}
                      name: ${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
          output:
              to:
                  kind: ImageStreamTag
                  name: ${NAME}:${OUTPUT_IMAGE_TAG}
parameters:
    - name: NAME
      displayName: Name
      description: The name assigned to all of the resources defined in this template.
      required: true
      value: db
    - name: SUFFIX
      displayName: Suffix
      description: A name suffix used for all objects
      required: false
      value: -primary
    - name: APP_NAME
      displayName: App Name
      description: Used to group components together in the OpenShift console.
      required: true
      value: EmprPermitAgent
    - name: APP_GROUP
      displayName: App Group
      description: The name assigned to all of the deployments in this project.
      required: true
      value: primary-instance
    - name: GIT_REPO_URL
      displayName: Git Repo URL
      description: The URL to your GIT repo.
      required: true
      value: https://github.com/WadeBarnes/von-bc-registries-agent-configurations.git
    - name: GIT_REF
      displayName: Git Reference
      description: The git reference or branch.
      required: true
      value: feature/ocp4
    - name: SOURCE_CONTEXT_DIR
      displayName: Source Context Directory
      description: The source context directory.
      required: false
      value: openshift/templates/db/config
    - name: SOURCE_IMAGE_KIND
      displayName: Source Image Kind
      description:
          The 'kind' (type) of the  source image; typically ImageStreamTag, or
          DockerImage.
      required: true
      value: DockerImage
    - name: SOURCE_IMAGE_NAME
      displayName: Source Image Name
      required: true
      description: The name of the source image.
      value: registry.access.redhat.com/rhscl/postgresql-10-rhel7
    - name: SOURCE_IMAGE_TAG
      displayName: Source Image Tag
      required: true
      description: The tag of the source image.
      value: latest
    - name: OUTPUT_IMAGE_TAG
      displayName: Output Image Tag
      description: The tag given to the built image.
      required: true
      value: latest
